# Book settings
title: Notes on metabolic modelling analysis
author: Haris Zafeiropoulos
copyright: "2024"
logo: logo.png # The logo gets the notebooks/ as root

execute:
  timeout: -1
  execute_notebooks: force

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    language: en
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    myst_enable_extensions:
      - amsmath
      - dollarmath
      - attrs_inline
      - colon_fence
      - deflist
      - fieldlist
      - html_admonition
      - html_image
      - linkify
      - replacements
      - smartquotes
      - strikethrough
      - substitution
      - tasklist

html:
  favicon: favicon.png
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/hariszaf/notes-on-met-mod-analysis
  path_to_book: notebooks
  branch: master

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
